feat(KL-133): create product like API
taco-official/klkl-server pull request #38
Opened 2024-08-08 07:37 UTC by idealflower-k

## 📌 연관된 이슈
[KL-133/상품 좋아요 api 구현](https://ohhamma.atlassian.net/browse/KL-133)

## 📝 작업 내용
- 상품 좋아요 POST 구현
- 상품 좋아요 DELETE 구현
- 상품 좋아요수 증가, 감소 함수 추가
- 상품 ID로 엔티티 get함수 추가
- 유저 현재 사용자 get 함수 추가 (현재는 test유저 반환)
- 상품 테스트 코드 추가
- 좋아요 테스트 코드 추가

## 🌳 작업 브랜치명
KL-133/상품-좋아요-api-구현

## 📸 스크린샷 (선택)

## 💬 리뷰 요구사항 (선택)

2024-08-08 07:39 UTC, idealflower-k commented
@coderabbitai review

2024-08-08 07:48 UTC, ohhamma commented on src/main/java/taco/klkl/domain/product/domain/Product.java
메소드에 줄바꿈이 너무 많습니다.. 코드가 짧아서 없애도 될 것 같습니다.

2024-08-08 07:51 UTC, ohhamma commented on src/main/java/taco/klkl/domain/product/service/ProductService.java
여기 메소드명을 동일하게 increase/decrease로 가는게 좋을 것 같습니다. count값을 올리고 내리는 의미로 만들어줍시다 !

2024-08-08 07:52 UTC, ohhamma commented on src/test/java/taco/klkl/domain/product/domain/ProductTest.java
좋아요수가 경계값에서 증가 / 감소하는 경우에 대한 테스트도 필요할 것 같습니다.

2024-08-08 07:54 UTC, ohhamma commented on src/main/java/taco/klkl/domain/product/domain/Product.java
> +			return;
이 경우에는 예외를 던지는게 좋을 것 같습니다.

2024-08-08 07:58 UTC, ohhamma commented on src/main/resources/database/data.sql
상품 더미 데이터를 제가 id 101번으로 하나 만들어두어서 상화님 번호로 상품 더미 데이터 하나 더 추가해야할 것 같습니다 !

2024-08-08 07:59 UTC, ohhamma commented on src/main/java/taco/klkl/domain/like/domain/Like.java
> +		@UniqueConstraint(columnNames = {"product_id", "user_id"})
unique 설정을 이렇게 필드 조합에도 줄 수 있군요 !

2024-08-08 08:00 UTC, ohhamma commented on src/main/java/taco/klkl/domain/like/domain/Like.java
> +	@ManyToOne(fetch = FetchType.LAZY)
모든 엔티티 매핑 어노테이션에 `optional = false` 옵션도 추가해주세요 !

2024-08-08 08:00 UTC, idealflower-k commented on src/main/java/taco/klkl/domain/product/domain/Product.java
> +			return;
클라이언트에게 에러 응답이 나갈텐데 괜찮을까요? 클라이언트는 굳이 이 에러를 받을 필요는 없어 보여서요

2024-08-08 08:04 UTC, ohhamma commented on src/main/java/taco/klkl/domain/like/service/LikeServiceImpl.java
> +	private boolean isLikeAlreadyExists(Product product, User user) {
이 메소드명을 조금 수정해봅시다.
- `existsByProductAndUser`
- `isLikePresent`

둘 중에 하나로 바꾸면 좋을 것 같습니다 !

2024-08-08 08:05 UTC, ohhamma commented on src/main/java/taco/klkl/domain/like/controller/LikeController.java
> +	void addLike(@PathVariable(value = "id") final Long productId) {
접근제어자를 명시해줍시다.

2024-08-08 08:10 UTC, ohhamma commented on src/test/java/taco/klkl/domain/like/integration/LikeIntegrationTest.java
> +		user = userUtil.findTestUser();
이 코드가 service에서의 코드와 일치하지 않는 것 같습니다. `getCurrentUser()`로 메소드 수정 부탁드려요 !

2024-08-08 08:13 UTC, ohhamma commented on src/test/java/taco/klkl/domain/like/integration/LikeIntegrationTest.java
> +		Assertions.assertThat(all).hasSize(1);
`Assertions`를 Import할 때 클래스 메소드까지 모두 import해오고, 테스트코드에서는 `assertThat`만 사용하는 형식으로 수정하면 부탁드립니다! 이전 코드에서 작성한 일관성을 가져가면 좋을 것 같아요.

2024-08-08 08:14 UTC, ohhamma commented on src/test/java/taco/klkl/domain/like/service/LikeServiceImplTest.java
> +		verify(productService, never()).addLikeCount(product);
메소드 호출이 안 일어나길 원한다면 이렇게 테스트코드를 작성할 수 있군요 !

2024-08-08 08:15 UTC, ohhamma commented on src/main/java/taco/klkl/domain/like/domain/Like.java
> +		optional = false
이 부분 나중에 넣어주셨군요! 확인했습니다.

2024-08-08 08:16 UTC, ohhamma requested changes
작성하신 코드 확인했습니다! 코멘트에 남긴 내용들을 확인하시고 수정해서 다시 코드리뷰 요청해주세요.

2024-08-08 08:16 UTC, idealflower-k commented on src/main/java/taco/klkl/domain/product/domain/Product.java
> +			return;
아니네요 프론트엔드에서 좋아요수 증가, 감소를 안하도록 보내줘야 겠네요.
추가로 좋아요 POST, DELET시 완료된 좋아요수를 보내 주는게 좋을까요?

2024-08-08 08:18 UTC, idealflower-k commented on src/main/java/taco/klkl/domain/product/domain/Product.java
> +			return;
요청 처리 완료된 좋아요수를 전달해주면 프론트에서 +1, -1같은 연산이 아닌 api에 의존할 수 있어서 좋아보이기도 하네요

2024-08-08 08:55 UTC, ohhamma commented on src/main/java/taco/klkl/domain/product/domain/Product.java
> +			return;
좋은 것 같습니다! post랑 delete 둘 다 `200` OK로 통일하는게 좋을 것 같네요.

2024-08-09 04:28 UTC, idealflower-k commented on src/main/java/taco/klkl/domain/product/domain/Product.java
수정했습니다!

2024-08-09 04:28 UTC, idealflower-k commented on src/main/java/taco/klkl/domain/product/service/ProductService.java
수정했습니다!

2024-08-09 04:29 UTC, idealflower-k commented on src/test/java/taco/klkl/domain/product/domain/ProductTest.java
단위 테스트로 추가했습니다!

2024-08-09 04:29 UTC, idealflower-k commented on src/main/java/taco/klkl/domain/product/domain/Product.java
> +			return;
수정했습니다!

2024-08-09 04:29 UTC, idealflower-k commented on src/main/resources/database/data.sql
1번 그대로 두면 에러 발생해서 101로만 수정했습니다!

2024-08-09 04:30 UTC, idealflower-k commented on src/main/java/taco/klkl/domain/like/service/LikeServiceImpl.java
> +	private boolean isLikeAlreadyExists(Product product, User user) {
`isLikePresent`로 수정했습니다!

2024-08-09 04:30 UTC, idealflower-k commented on src/main/java/taco/klkl/domain/like/controller/LikeController.java
> +	void addLike(@PathVariable(value = "id") final Long productId) {
수정했습니다!

2024-08-09 04:31 UTC, idealflower-k commented on src/test/java/taco/klkl/domain/like/integration/LikeIntegrationTest.java
> +		user = userUtil.findTestUser();
User가 필요없어서 코드를 삭제했습니다!

2024-08-09 04:31 UTC, idealflower-k commented on src/test/java/taco/klkl/domain/like/integration/LikeIntegrationTest.java
> +		Assertions.assertThat(all).hasSize(1);
static으로 import했습니다!

2024-08-09 04:31 UTC, idealflower-k commented on src/test/java/taco/klkl/domain/like/service/LikeServiceImplTest.java
> +		verify(productService, never()).addLikeCount(product);
이렇게 테스트할 수 있어서 좋더라구요!

2024-08-09 13:41 UTC, min3m commented on src/main/java/taco/klkl/domain/like/domain/Like.java
> +		@UniqueConstraint(columnNames = {"product_id", "user_id"})
테이블 어노테이션이 갖는 의미는 무엇인가요? `@UniqueConstraint` 어노테이션을 유니크 컬럼을 한 번에 정의해주는 건가요?

2024-08-09 13:43 UTC, min3m commented on src/main/java/taco/klkl/domain/like/service/LikeServiceImpl.java
> +public class LikeServiceImpl implements LikeService {
확실히 인터페이스를 상속 받는 방향으로 구현하는게 좋아보이는 것 같습니다!

2024-08-10 06:43 UTC, min3m commented on src/main/java/taco/klkl/domain/like/controller/LikeController.java
> +	@ResponseStatus(value = HttpStatus.OK)
Delete 매서드에서 NO_CONTENT에서 OK로 변경하신 이유가 있나요? NO_CONTENT면 아예 response가 없어야돼서 인가요?

2024-08-10 07:01 UTC, min3m commented on src/test/java/taco/klkl/domain/like/service/LikeServiceImplTest.java
> +		when(productService.increaseLikeCount(product)).thenThrow(LikeCountMaximumException.class);
when과 dothrow로 예외를 던져주신건 assertThatThrownBy로 예외가 잘 반환되는지 확인하기 위해서 인가요?

2024-08-10 07:16 UTC, min3m submitted a review, later dismissed
좋아요 수 관련 PR 잘 봤습니다! 커밋 내용들 보다보니 저랑 조금씩 다른 부분들이 있어서 코멘트로 남겨놨습니다!!

2024-08-12 09:08 UTC, idealflower-k commented on src/main/java/taco/klkl/domain/like/controller/LikeController.java
> +	@ResponseStatus(value = HttpStatus.OK)
좋아요 API의 응답으로 현재 좋아요 수와 사용자가 좋아요를 눌렀는지 여부를 전달해주는 방식으로 수정해서 OK로 변경하였습니다!

2024-08-12 09:09 UTC, idealflower-k commented on src/test/java/taco/klkl/domain/like/service/LikeServiceImplTest.java
> +		when(productService.increaseLikeCount(product)).thenThrow(LikeCountMaximumException.class);
넵 서비스까지 하위 계층에서 발생한 exception이 잘 전달 되는지 확인하기 위한 테스트여서 when, doThrow를 사용했습니다!

2024-08-12 09:22 UTC, ohhamma commented on src/main/java/taco/klkl/global/error/exception/ErrorCode.java
> +	LIKE_COUNT_MINIMUM(HttpStatus.BAD_REQUEST, "C031", "상품의 좋아요수가 최소값입니다. 0"),
에러코드 이름을 `LIKES_OVER_MAXIMUM`과 `LIKES_BELOW_MIMIMUM`로 변경하는 건 어떤가요? 예외이름도 여기에 맞게 변경해주세요 !

2024-08-12 10:14 UTC, idealflower-k commented on src/main/java/taco/klkl/global/error/exception/ErrorCode.java
> +	LIKE_COUNT_MINIMUM(HttpStatus.BAD_REQUEST, "C031", "상품의 좋아요수가 최소값입니다. 0"),
수정했습니다!

2024-08-13 04:12 UTC, min3m submitted a review, later dismissed
좋아요 수 관련 PR 잘 봤습니다! 커밋 내용들 보다보니 저랑 조금씩 다른 부분들이 있어서 코멘트로 남겨놨습니다!!

2024-08-13 04:18 UTC, ohhamma commented on src/main/java/taco/klkl/global/error/exception/ErrorCode.java
> +	LIKE_COUNT_MINIMUM(HttpStatus.BAD_REQUEST, "C031", "상품의 좋아요수가 최소값입니다. 0"),
앗.. `LIKES` 대신 `LIKE_COUNT`으로 이름 변경해주세요 !

2024-08-13 05:43 UTC, idealflower-k commented on src/main/java/taco/klkl/global/error/exception/ErrorCode.java
> +	LIKE_COUNT_MINIMUM(HttpStatus.BAD_REQUEST, "C031", "상품의 좋아요수가 최소값입니다. 0"),
수수정했습니다!

2024-08-13 05:48 UTC, ohhamma commented
수정하신 내용 모두 확인했습니다! 수고하셨습니다 :)

2024-08-13 05:48 UTC, ohhamma approved these changes
수정하신 내용 모두 확인했습니다! 수고하셨습니다 :)

2024-08-13 05:55 UTC, min3m approved these changes
좋아요 수 관련 PR 잘 봤습니다! 커밋 내용들 보다보니 저랑 조금씩 다른 부분들이 있어서 코멘트로 남겨놨습니다!!

2024-08-13 05:57 UTC, merged